/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PeladaRouteImport } from './routes/pelada'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminJogadoresRouteImport } from './routes/admin.jogadores'
import { Route as AdminPeladaRouteImport } from './routes/admin.pelada'
import { Route as AdminTimesRouteImport } from './routes/admin.times'
import { Route as HistoricoIndexRouteImport } from './routes/historico.index'
import { Route as HistoricoPeladaIdRouteImport } from './routes/historico.$peladaId'
import { Route as JogadoresIndexRouteImport } from './routes/jogadores.index'
import { Route as JogadoresIdRouteImport } from './routes/jogadores.$id'
import { Route as PartidaIdRouteImport } from './routes/partida.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaRoute = PeladaRouteImport.update({
  id: '/pelada',
  path: '/pelada',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogadoresRoute = AdminJogadoresRouteImport.update({
  id: '/admin/jogadores',
  path: '/admin/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeladaRoute = AdminPeladaRouteImport.update({
  id: '/admin/pelada',
  path: '/admin/pelada',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimesRoute = AdminTimesRouteImport.update({
  id: '/admin/times',
  path: '/admin/times',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/historico/',
  path: '/historico/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoPeladaIdRoute = HistoricoPeladaIdRouteImport.update({
  id: '/historico/$peladaId',
  path: '/historico/$peladaId',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIndexRoute = JogadoresIndexRouteImport.update({
  id: '/jogadores/',
  path: '/jogadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIdRoute = JogadoresIdRouteImport.update({
  id: '/jogadores/$id',
  path: '/jogadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaIdRoute = PartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin': typeof AdminIndexRoute
  '/historico': typeof HistoricoIndexRoute
  '/jogadores': typeof JogadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin/'
    | '/historico/'
    | '/jogadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin'
    | '/historico'
    | '/jogadores'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin/'
    | '/historico/'
    | '/jogadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PeladaRoute: typeof PeladaRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  AdminJogadoresRoute: typeof AdminJogadoresRoute
  AdminPeladaRoute: typeof AdminPeladaRoute
  AdminTimesRoute: typeof AdminTimesRoute
  HistoricoPeladaIdRoute: typeof HistoricoPeladaIdRoute
  JogadoresIdRoute: typeof JogadoresIdRoute
  PartidaIdRoute: typeof PartidaIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
  JogadoresIndexRoute: typeof JogadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada': {
      id: '/pelada'
      path: '/pelada'
      fullPath: '/pelada'
      preLoaderRoute: typeof PeladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogadores': {
      id: '/admin/jogadores'
      path: '/admin/jogadores'
      fullPath: '/admin/jogadores'
      preLoaderRoute: typeof AdminJogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pelada': {
      id: '/admin/pelada'
      path: '/admin/pelada'
      fullPath: '/admin/pelada'
      preLoaderRoute: typeof AdminPeladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/times': {
      id: '/admin/times'
      path: '/admin/times'
      fullPath: '/admin/times'
      preLoaderRoute: typeof AdminTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$peladaId': {
      id: '/historico/$peladaId'
      path: '/historico/$peladaId'
      fullPath: '/historico/$peladaId'
      preLoaderRoute: typeof HistoricoPeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/': {
      id: '/jogadores/'
      path: '/jogadores'
      fullPath: '/jogadores/'
      preLoaderRoute: typeof JogadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$id': {
      id: '/jogadores/$id'
      path: '/jogadores/$id'
      fullPath: '/jogadores/$id'
      preLoaderRoute: typeof JogadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$id': {
      id: '/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof PartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PeladaRoute: PeladaRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  AdminJogadoresRoute: AdminJogadoresRoute,
  AdminPeladaRoute: AdminPeladaRoute,
  AdminTimesRoute: AdminTimesRoute,
  HistoricoPeladaIdRoute: HistoricoPeladaIdRoute,
  JogadoresIdRoute: JogadoresIdRoute,
  PartidaIdRoute: PartidaIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
  JogadoresIndexRoute: JogadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
