/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PeladaRouteImport } from './routes/pelada'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAcessosRouteImport } from './routes/admin.acessos'
import { Route as AdminJogadoresRouteImport } from './routes/admin.jogadores'
import { Route as AdminPeladaRouteImport } from './routes/admin.pelada'
import { Route as AdminTimesRouteImport } from './routes/admin.times'
import { Route as HistoricoIndexRouteImport } from './routes/historico.index'
import { Route as HistoricoPeladaIdRouteImport } from './routes/historico.$peladaId'
import { Route as JogadoresIndexRouteImport } from './routes/jogadores.index'
import { Route as JogadoresIdRouteImport } from './routes/jogadores.$id'
import { Route as PartidaIdRouteImport } from './routes/partida.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaRoute = PeladaRouteImport.update({
  id: '/pelada',
  path: '/pelada',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/admin/acessos',
  path: '/admin/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogadoresRoute = AdminJogadoresRouteImport.update({
  id: '/admin/jogadores',
  path: '/admin/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeladaRoute = AdminPeladaRouteImport.update({
  id: '/admin/pelada',
  path: '/admin/pelada',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimesRoute = AdminTimesRouteImport.update({
  id: '/admin/times',
  path: '/admin/times',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIndexRoute = HistoricoIndexRouteImport.update({
  id: '/historico/',
  path: '/historico/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoPeladaIdRoute = HistoricoPeladaIdRouteImport.update({
  id: '/historico/$peladaId',
  path: '/historico/$peladaId',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIndexRoute = JogadoresIndexRouteImport.update({
  id: '/jogadores/',
  path: '/jogadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIdRoute = JogadoresIdRouteImport.update({
  id: '/jogadores/$id',
  path: '/jogadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaIdRoute = PartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin': typeof AdminIndexRoute
  '/historico': typeof HistoricoIndexRoute
  '/jogadores': typeof JogadoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/pelada': typeof PeladaRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/pelada': typeof AdminPeladaRoute
  '/admin/times': typeof AdminTimesRoute
  '/historico/$peladaId': typeof HistoricoPeladaIdRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/partida/$id': typeof PartidaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/historico/': typeof HistoricoIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/admin/acessos'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin/'
    | '/historico/'
    | '/jogadores/'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/admin/acessos'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin'
    | '/historico'
    | '/jogadores'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/aguardando'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/pelada'
    | '/perfil'
    | '/ranking'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/admin/acessos'
    | '/admin/jogadores'
    | '/admin/pelada'
    | '/admin/times'
    | '/historico/$peladaId'
    | '/jogadores/$id'
    | '/partida/$id'
    | '/admin/'
    | '/historico/'
    | '/jogadores/'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AguardandoRoute: typeof AguardandoRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PeladaRoute: typeof PeladaRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminJogadoresRoute: typeof AdminJogadoresRoute
  AdminPeladaRoute: typeof AdminPeladaRoute
  AdminTimesRoute: typeof AdminTimesRoute
  HistoricoPeladaIdRoute: typeof HistoricoPeladaIdRoute
  JogadoresIdRoute: typeof JogadoresIdRoute
  PartidaIdRoute: typeof PartidaIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HistoricoIndexRoute: typeof HistoricoIndexRoute
  JogadoresIndexRoute: typeof JogadoresIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada': {
      id: '/pelada'
      path: '/pelada'
      fullPath: '/pelada'
      preLoaderRoute: typeof PeladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/admin/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogadores': {
      id: '/admin/jogadores'
      path: '/admin/jogadores'
      fullPath: '/admin/jogadores'
      preLoaderRoute: typeof AdminJogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pelada': {
      id: '/admin/pelada'
      path: '/admin/pelada'
      fullPath: '/admin/pelada'
      preLoaderRoute: typeof AdminPeladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/times': {
      id: '/admin/times'
      path: '/admin/times'
      fullPath: '/admin/times'
      preLoaderRoute: typeof AdminTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/': {
      id: '/historico/'
      path: '/historico'
      fullPath: '/historico/'
      preLoaderRoute: typeof HistoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$peladaId': {
      id: '/historico/$peladaId'
      path: '/historico/$peladaId'
      fullPath: '/historico/$peladaId'
      preLoaderRoute: typeof HistoricoPeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/': {
      id: '/jogadores/'
      path: '/jogadores'
      fullPath: '/jogadores/'
      preLoaderRoute: typeof JogadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$id': {
      id: '/jogadores/$id'
      path: '/jogadores/$id'
      fullPath: '/jogadores/$id'
      preLoaderRoute: typeof JogadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$id': {
      id: '/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof PartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AguardandoRoute: AguardandoRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PeladaRoute: PeladaRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAcessosRoute: AdminAcessosRoute,
  AdminJogadoresRoute: AdminJogadoresRoute,
  AdminPeladaRoute: AdminPeladaRoute,
  AdminTimesRoute: AdminTimesRoute,
  HistoricoPeladaIdRoute: HistoricoPeladaIdRoute,
  JogadoresIdRoute: JogadoresIdRoute,
  PartidaIdRoute: PartidaIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HistoricoIndexRoute: HistoricoIndexRoute,
  JogadoresIndexRoute: JogadoresIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
